<?php

namespace RobotsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RobotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RobotRepository extends EntityRepository
{

    /*public function findAll()
    {
        $query = $this->createQueryBuilder('r')
            ->select('partial r.{id,name,type,year}')
            ->getQuery();

        return $query->getResult();
    }*/

    public function searchByName($name)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.name LIKE :name')
            ->setParameter('name', '%'.$name.'%')
            ->getQuery();

        return $query->getResult();
    }

}
